[package]
name = "sesame"
version = "0.1.0"
authors = ["Kinan Dak Albab <kinan_dak_albab@alumni.brown.edu>", 
           "Artem Agvanian <artemagvanian@icloud.com>",
           "Corinn Tiffany <94402869+corinnt@users.noreply.github.com>",
           "Allen Aby <allen.aby@gmail.com>",
           "Alexander Portland <alexanderportland1@gmail.com>",
           "Sarah Ridley <sarah_ridley@brown.edu>",           
           "Malte Schwarzkopf <malte@cs.brown.edu>"]
edition = "2018"

[lib]
name = "sesame"
path = "src/lib.rs"

[dependencies]
sesame_sandbox = { path = "../sandbox" }

async-trait = { version = "0.1.79" }
chrono = "^0.4"
dyn-clone = "1.0.20"
either = "1.10.0"
erased-serde = "0.3.25"
itertools = "0.12.1"
mysql_common = "0.27.5"
pin-project-lite = "0.2.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Optional dependencies.
sesame_derive = { path = "../derive", optional = true }

[dev-dependencies]
static_assertions = "1.1.0"

[features]
default = ["derive"]
derive = ["sesame_derive"]
sandbox_timing = ["sesame_sandbox/sandbox_timing"]
