[package]
name = "sesame"
version = "0.1.0"
authors = ["Kinan Dak Albab <kinan_dak_albab@alumni.brown.edu>", 
           "Artem Agvanian <artemagvanian@icloud.com>",
           "Corinn Tiffany <94402869+corinnt@users.noreply.github.com>",
           "Allen Aby <allen.aby@gmail.com>",
           "Alexander Portland <alexanderportland1@gmail.com>",
           "Sarah Ridley <sarah_ridley@brown.edu>",           
           "Malte Schwarzkopf <malte@cs.brown.edu>"]
edition = "2018"

[lib]
name = "sesame"
path = "src/lib.rs"

[dependencies]
pin-project-lite = "0.2.14"
alohomora_derive = { path = "../../alohomora_derive", optional = true }
alohomora_sandbox = { path = "../../alohomora_sandbox" }
chrono = "^0.4"
either = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
erased-serde = "0.3.25"
itertools = "0.12.1"
dyn-clone = "1.0.20"

[dev-dependencies]
static_assertions = "1.1.0"

[features]
default = ["derive"]
derive = ["alohomora_derive"]
sandbox_timing = ["alohomora_sandbox/sandbox_timing"]

[patch.crates-io]
funty = { git = "https://github.com/bitvecto-rs/funty/", rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446" }
