[package]
name = "sesame_sandbox"
version = "0.1.0"
authors = ["Kinan Dak Albab <kinan.bab.14@gmail.com>",
           "Alexander Portland <alexanderportland1@gmail.com>",
           "Allen Aby <allen.aby@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.0", features = ["serde"] }

[features]
default = []
sandbox_timing = []
