[package]
name = "sesame_lints"
version = "0.1.0"
authors = ["corinn_tiffany@brown.edu",
           "alexander_portland@brown.edu",
           "kinan_dak_albab@brown.edu"]
description = "Lints for ensuring Sesame applications respect Sesame's' static requirements"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[[example]]
name = "sesame_type_illegal"
path = "examples/sesame_type_illegal.rs"

[[example]]
name = "sesame_type_legal"
path = "examples/sesame_type_legal.rs"

[[example]]
name = "sesame_sandbox_illegal"
path = "examples/sesame_sandbox_illegal.rs"

[[example]]
name = "sesame_sandbox_legal"
path = "examples/sesame_sandbox_legal.rs"

[[example]]
name = "sesame_sandbox_transfer_legal"
path = "examples/sesame_sandbox_transfer_legal.rs"

[[example]]
name = "sesame_sandbox_transfer_illegal"
path = "examples/sesame_sandbox_transfer_illegal.rs"

[[example]]
name = "sesame_pcr_legal"
path = "examples/sesame_pcr_legal.rs"

[[example]]
name = "sesame_pcr_illegal"
path = "examples/sesame_pcr_illegal.rs"

[dependencies]
base64 = "0.22.0"
paste = "1.0"
clippy_utils = { git = "https://github.com/artemagvanian/rust-clippy-nightly-2023-04-12", rev = "88cd75c5ecb95c4dfbe8ebc4dd5732edd8652ed8" }
dylint_linting = "=2.5.0"
if_chain = "1.0.2"
reqwest = { version = "0.12.2", features = ["blocking"] }
# TODO change scrutils dep to git = "https://github.com/artemagvanian/scrutinizer.git"
# make sure this points to the `pcr-signing` branch of scrutils
scrutils = { git = "https://github.com/brownsys/scrutinizer.git", branch = "pcr-signing" } #{ path = "../../scrutinizer/scrutils" }
syn = { version = "2.0.58", features = ["full"]}
quote = "1.0.37"
proc-macro2 = "1.0.86"
sha2 = "0.10.8"
hex = "0.4.3"

[dev-dependencies]
dylint_testing = "=2.5.0"
sesame = { path = "../core" }
sesame_sandbox = { path = "../sandbox" }

[package.metadata.rust-analyzer]
rustc_private = true

[patch.crates-io]
funty = { git = "https://github.com/bitvecto-rs/funty/", rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446" }
