[package]
name = "sesame_mysql"
version = "0.1.0"
authors = ["Kinan Dak Albab <kinan_dak_albab@alumni.brown.edu>"]
edition = "2018"

[lib]
name = "sesame_mysql"
path = "src/lib.rs"

[dependencies]
sesame = { path = "../core" }

lazy_static = "1.4.0"
mysql = "21.0.2"
small_ctor = "0.1.2"

# Optional dependencies.
sesame_derive = { path = "../derive", optional = true }

[features]
default = ["derive"]
derive = ["sesame_derive"]