[package]
name = "example-sandbox-bin"
version = "0.1.0"
authors = ["Kinan Dak Albab <kinan_dak_albab@alumni.brown.edu>", 
           "Artem Agvanian <artemagvanian@icloud.com>",
           "Corinn Tiffany <94402869+corinnt@users.noreply.github.com>",
           "Allen Aby <allen.aby@gmail.com>",
           "Alexander Portland <alexanderportland1@gmail.com>",
           "Sarah Ridley <sarah_ridley@brown.edu>",           
           "Malte Schwarzkopf <malte@cs.brown.edu>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "bin"
path = "src/bin.rs"

[dependencies]
sesame = { path = "../../core" }
sandbox_test_lib = { path = "../../../tests/sandbox_test_lib" }
#sesame_sandbox = { path = "../sandbox" }

#async-trait = { version = "0.1.79" }
#chrono = "^0.4"
#dyn-clone = "1.0.20"
#either = "1.10.0"
#erased-serde = "0.3.25"
#itertools = "0.12.1"
#pin-project-lite = "0.2.14"
#serde = { version = "1.0", features = ["derive"] }
#serde_json = "1.0"

# Optional dependencies.

[build-dependencies]
sesame_build = { path = "../../build" }
