[package]
name = "dep_change_illegal"
version = "0.1.0"
authors = ["corinn_tiffany@brown.edu"]
edition = "2018"

[dependencies]
alohomora = { path = "../../alohomora" }
dependency = { path = "../dependency" }
