[package]
name = "sesame_derive"
version = "0.1.0"
authors = ["Kinan Dak Albab <kinan_dak_albab@alumni.brown.edu>",
           "Corinn Tiffany <94402869+corinnt@users.noreply.github.com>",
           "Alexander Portland <alexanderportland1@gmail.com>",
           "Malte Schwarzkopf <malte@cs.brown.edu>"]
edition = "2018"

[lib]
name = "sesame_derive"
proc-macro = true

[dependencies]
attribute-derive = "0.8.1"
proc-macro2 = "1.0.58"
quote = "1.0.27"
rocket_http = { git = "https://github.com/KinanBab/Rocket.git", branch = "main" }
serde = "1.0"
syn = { version = "2.0.16", features = [ "full" ] }

[dev-dependencies]
sesame = { path = "../core", default-features = false, features = [] }
sesame_mysql = { path = "../mysql", default-features = false, features = [] }
sesame_rocket = { path = "../rocket", default-features = false, features = [] }

erased-serde = "0.3.25"
mysql = "21.0.2"
rocket = { git = "https://github.com/KinanBab/Rocket.git", branch = "main" }
static_assertions = "1.1.0"
serde_json = "1.0"