[package]
name = "example_sandbox_lib"
version = "0.1.0"
authors = ["Kinan Dak Albab <kinan.bab.14@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sesame_derive = { path = "../../../sesame/derive" }
sesame_sandbox = { path = "../../../sesame/sandbox" } #, features = ["sandbox_timing"] }

[build-dependencies]
sesame_build = { path = "../../../sesame/build" }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[package.metadata]
sandboxes = [
  "add_numbers",
  "div_numbers",
  "mult_numbers"
]
